const cst = {
    ADD_DPT = "ADD_DPT",
    ADD_DPT_SUCCESS = "ADD_DPT_SUCCESS",

    ADD_MANAGER = "",
    ADD_MANAGER_SUCCESS = "",

    ADD_EMP_DPT = "ADD_EMP_DPT",
    ADD_EMP_DPT_SUCCESS = "ADD_EMP_DPT_SUCCESS",
    
    ADD_EMP = "ADD_EMP",
    ADD_EMP_SUCCESS = "ADD_EMP_SUCCESS",
    
    ADD_SALARY = "ADD_SALARY",
    ADD_SALARY_SUCCESS = "ADD_SALARY_SUCCESS",
    
    ADD_TITLE = "ADD_TITLE",
    ADD_TITLE_SUCCESS = "ADD_TITLE_SUCCESS",
    
    DISPLAY_DPT_BY_ID = "DISPLAY_DPT_BY_ID",
    DISPLAY_DPT_BY_ID_SUCCESS = "DISPLAY_DPT_BY_ID_SUCCESS",
    
    DISPLAY_DPT = "DISPLAY_DPT",
    DISPLAY_DPT_SUCCESS = "DISPLAY_DPT_SUCCESS",
    
    DISPLAY_EMP_BY_ID = "DISPLAY_EMP_BY_ID",
    DISPLAY_EMP_BY_ID_SUCCESS = "DISPLAY_EMP_BY_ID_SUCCESS",
    
    DISPLAY_EMP = "DISPLAY_EMP",
    DISPLAY_EMP_SUCCESS = "DISPLAY_EMP_SUCCESS",
    
    DELETE_EMP = "DELETE_EMP",
    DELETE_EMP_SUCCESS = "DELETE_EMP_SUCCESS",
    
    DELETE_DPT = "DELETE_DPT",
    DELETE_DPT_SUCCESS = "DELETE_DPT_SUCCESS",
    
    LINK_EMP_2_DPT = "LINK_EMP_2_DPT",
    LINK_EMP_2_DPT_SUCCESS = "LINK_EMP_2_DPT_SUCCESS",
    
    LINK_MANAGER_2_DPT = "LINK_MANAGER_2_DPT",
    LINK_MANAGER_2_DPT_SUCCESS = "LINK_MANAGER_2_DPT_SUCCESS",
    
    MENU_ADD: "MENU_ADD",
    MENU_DISPLAY: "MENU_DISPLAY",
    MENU_UPDATE: "MENU_UPDATE",
}

export default cst